{
    'name': 'JHM Contact Fields',
    'version': '19.0.1.1.0',
    'summary': 'Custom fields for JHM contacts and CRM leads',
    'category': 'Technical',
    'depends': ['base', 'contacts', 'crm', 'crm_iap_mine', 'documents', 'sale', 'sale_crm', 'sale_project', 'project', 'account', 'jhm_partner_fullname'],
    'data': [
        'security/ir.model.access.csv',
        'security/crm_stage_rules.xml',
        'data/jhm_data.xml',
        'views/res_partner_views.xml',
        'views/crm_lead_views.xml',
        'views/daily_sales_report_wizard.xml',
        'views/sales_mtd_report.xml',
        'views/ready_to_close_report.xml',
        'views/sales_report.xml',
        'views/sales_channel_report.xml',
        'views/lead_reports.xml',
        'views/jhm_crm_import_wizard_views.xml',
        'views/jhm_crm_contact_sync_wizard_views.xml',
        'views/project_task_views.xml',
        'report/jhm_invoice_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'jhm_contact_fields/static/src/css/chatter_width.css',
            'jhm_contact_fields/static/src/js/import_patch.js',
            'jhm_contact_fields/static/src/xml/import_progress.xml',
            'jhm_contact_fields/static/src/js/import_progress.js',
        ],
    },
    'post_init_hook': '_post_init_hook',
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
